### ISSUE TITLE
Bad version of wkhtmltopdf in tag 0.12.5-alpine3.10

### ISSUE THREAD

**Issue by floviolleau** [madnight/docker-alpine-wkhtmltopdf#21]
Hi,

I think you made a mistake regarding your tags.

If I docker pull the tag:
- 0.12.5-alpine3.10-3660174986, I get wkhtmltopdf **0.12.6**
- 0.12.5-alpine3.10, I get wkhtmltopdf **0.12.6**
- 0.12.5-alpine3.10-3550361538, I get wkhtmltopdf **0.12.6**
- 0.12.5-alpine3.10-3543388771, I get wkhtmltopdf **0.12.5**

![image](https://user-images.githubusercontent.com/5442973/206761563-5ebe99e5-c02d-42d1-9b40-d25179b9120c.png)

**Comment by madnight** [comment]
Should be fixed

**Comment by floviolleau** [comment]
Hi @madnight,

- 0.12.5-alpine3.10-3660174986, I get wkhtmltopdf 0.12.5 => OK
- 0.12.5-alpine3.10, I get wkhtmltopdf 0.12.5 => OK
- 0.12.5-alpine3.10-3550361538, I get wkhtmltopdf **0.12.6 => KO**
- 0.12.5-alpine3.10-3543388771, I get wkhtmltopdf 0.12.5 => OK

I still do not see 0.12.6 release. Latest was 2 years ago : 0.12.6-alpine3.10

Thanks a lot!

Side quest: move to alpine 3.16?
